location: .gitman
sources:
  - repo: https://github.com/TimLakemann/ami.git
    name: ami
    rev: robofly 
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: include/ami
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/TimLakemann/ami.git
    name: ami
    rev: 540321695532cc627fd5924c4774543837d14a21
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: include/ami
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
